version: '3.7'

services:
  web:
    build: .
    image: php7.3-apache
    container_name: gnuboard-web
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - gnunet


  db:
    image: mariadb:10.3.15
    container_name: gnuboard-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gnuboard
      MYSQL_USER: gnuuser
      MYSQL_PASSWORD: gnupass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gnunet

volumes:
  db_data:

networks:
  gnunet:
